CREATE DATABASE SistemaPIM;
GO

USE SistemaPIM;
GO

CREATE TABLE Usuario (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
    Telefone NVARCHAR(20) NOT NULL,
    CEP CHAR(8) NOT NULL,
    Endereco NVARCHAR(150) NOT NULL,
    Bairro NVARCHAR(100) NOT NULL,
    Complemento NVARCHAR(100) NULL
);